// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
)

const feeds = `-- name: Feeds :many

SELECT feeds.name, feeds.url, users.name AS user_name
FROM feeds
JOIN users 
ON users.id = feeds.user_id
`

type FeedsRow struct {
	Name     string
	Url      string
	UserName string
}

func (q *Queries) Feeds(ctx context.Context) ([]FeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, feeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedsRow
	for rows.Next() {
		var i FeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
